const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
(async()=>{
 const db=new PGlite();let passed=0;
 const check=(a,b,label)=>{assert.deepEqual(a,b);passed++;console.log('PASS '+label);};
 const row=async(sql,args=[]) => (await db.query(sql,args)).rows[0],scalar=async(sql,args=[])=>Object.values(await row(sql,args))[0];
 const fail=async(sql,args,label,pattern)=>{await assert.rejects(db.query(sql,args),pattern);passed++;console.log('PASS '+label);};
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb,last_accessed_at timestamptz,version text,updated_at timestamptz,unique(bucket_id,name));
 alter table storage.objects enable row level security;grant usage on schema public,auth,storage to anon,authenticated,service_role;
 grant select,insert,update,delete on storage.objects to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;
 alter default privileges in schema public grant execute on functions to anon,authenticated;`);
 const migrations=['202609120001_inventory.sql','202609130002_photo_order.sql','202609130003_photo_limit_30.sql','202609130004_super_admin.sql','202609130005_staff_profiles.sql','202609130006_customers.sql','202609140006_saved_vehicles.sql','202609140007_customer_workspace.sql','202609140008_loan_validation.sql','202609140009_loan_workflow.sql','202609140010_loan_documents.sql','202609140011_guest_intake.sql','202609140012_office_admin.sql','202609230001_optional_intake_vehicle.sql','202610080001_case_submissions.sql','202610090001_financing_admin_workspace.sql','202610100001_insurance_policy_review.sql'];
 for(const name of migrations)await db.exec(fs.readFileSync('supabase/migrations/'+name,'utf8'));
 const ids=Array.from({length:9},()=>randomUUID()),[owner,sales,sales2,office,office2,coordinator,account,customer,inactive]=ids;
 for(const [n,id] of ids.entries())await db.query('insert into auth.users values($1,$2,now())',[id,`synthetic-policy-${n}@example.test`]);
 for(const [id,role,active] of [[owner,'super_admin',true],[sales,'sales',true],[sales2,'sales',true],[office,'office_admin',true],[office2,'office_admin',true],[coordinator,'office_admin',true],[account,'account',true],[inactive,'office_admin',false]])await db.query('insert into public.staff_memberships(user_id,role,active) values($1,$2,$3)',[id,role,active]);
 const as=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec('set role '+(id?'authenticated':'anon'));};
 const root=async()=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub','',false)");};
 const car=await scalar("insert into public.vehicles(plate,brand,model,variant,year,engine_litres,transmission,fuel_type,price) values('SYNTH123','Synthetic','Car','Auto',2020,1.5,'Auto','PETROL',50000) returning id");
 const loan=await scalar("insert into public.loan_applications(customer_id,vehicle_id,assigned_sales,vehicle_summary,details,applicant_type,status,submitted_at) values($1,$2,$3,'{\"plate\":\"SYNTH123\"}','{\"name\":\"Fictional Customer\"}','worker','Submitted to E2',now()) returning id",[customer,car,sales]);
 const link=await scalar('insert into public.intake_links(vehicle_id,salesperson) values($1,$2) returning id',[car,sales2]);
 const intake=await scalar("insert into public.intake_submissions(link_id,write_hash,vehicle_id,salesperson,vehicle_summary,details,applicant_type,status,submitted_at) values($1,'abc'::bytea,$2,$3,'{\"plate\":\"SYNTH123\"}','{\"name\":\"Fictional Guest\"}','worker','Received by Salesman',now()) returning id",[link,car,sales2]);
 const c=await row("insert into public.finance_cases(loan_id,case_name,salesperson,office_admin,handed_at) values($1,'Synthetic loan policy',$2,$3,now()) returning *",[loan,sales,office]);
 const g=await row("insert into public.finance_cases(intake_id,case_name,salesperson,office_admin,handed_at) values($1,'Synthetic guest policy',$2,$3,now()) returning *",[intake,sales2,office2]);
 await db.query('insert into public.finance_dispatchers(user_id) values($1)',[coordinator]);
 const {extraction}=await import('../../tests/fixtures/insurance-fixtures.mjs');
 const reserveSQL='select * from public.e2_reserve_policy($1,$2,$3,$4,$5,$6)',finishSQL='select * from public.e2_finish_policy($1,$2,$3,$4)',saveSQL='select * from public.e2_save_policy_review($1,$2,$3,$4,$5,$6,$7,$8,$9)';
 const reserve=(target=c,hash='a',size=123,mime='application/pdf')=>row(reserveSQL,[target.id,target.revision,'synthetic-policy.pdf',mime,size,hash.repeat(64)]);
 const finish=(target,d,e=extraction)=>row(finishSQL,[target.id,d.id,target.revision,JSON.stringify(e)]);
 const upload=d=>db.query("insert into storage.objects(bucket_id,name,metadata) values('insurance-policies',$1,$2)",[d.path,JSON.stringify({size:d.byte_size,mimetype:d.mime_type})]);
 const args=(target,d,revision=0,patch={insurer:'Synthetic Assurance',registration:'SYNTH123',premium:'1250.50'},replace=[],reviewed=true,belongs=true)=>[target.id,d.id,target.revision,revision,JSON.stringify(patch),replace,reviewed,belongs,'Synthetic original and selected values checked.'];
 const workspace=target=>scalar('select public.e2_policy_workspace($1)',[target.id]);
 check(await scalar("select public from storage.buckets where id='insurance-policies'"),false,'Policy bucket is private');
 check(await scalar('select count(*)::int from public.insurance_policy_documents'),0,'Migration seeds no real documents');
 for(const id of [null,customer,account,sales2,office2,inactive]){
  await as(id);await fail('select public.e2_policy_workspace($1)',[c.id],'Unassigned/anonymous role cannot read case policy workspace');
  await fail(reserveSQL,[c.id,1,'synthetic.pdf','application/pdf',123,'a'.repeat(64)],'Unassigned/anonymous role cannot reserve policy file');
 }
 for(const id of [sales,coordinator]){await as(id);check((await workspace(c)).can_write,false,'Existing Sales/coordinator case access remains read-only for policy');await fail(reserveSQL,[c.id,1,'synthetic.pdf','application/pdf',123,'a'.repeat(64)],'Read-only staff cannot upload policy');}
 await as(office);
 for(const [size,mime,hash] of [[0,'application/pdf','a'.repeat(64)],[10485761,'application/pdf','a'.repeat(64)],[123,'text/html','a'.repeat(64)],[123,'application/pdf','invalid']])await fail(reserveSQL,[c.id,1,'synthetic.pdf',mime,size,hash],'Invalid file metadata rejected server-side');
 await fail(reserveSQL,[c.id,null,'synthetic.pdf','application/pdf',123,'a'.repeat(64)],'Missing case revision rejected');
 const d=await reserve();check(d.state,'uploading','Reservation saves no policy fields');check((await workspace(c)).record,null,'Fields remain empty before review');
 check((await reserve()).id,d.id,'Duplicate reservation reuses the same case-bound upload');
 await fail(reserveSQL,[c.id,1,'synthetic.pdf','application/pdf',999,'a'.repeat(64)],'Duplicate hash with conflicting metadata rejected');
 await fail(finishSQL,[c.id,d.id,1,JSON.stringify(extraction)],'Incomplete original cannot become ready');
 await fail(saveSQL,args(c,d),'Unfinished original cannot populate fields');
 await fail("insert into storage.objects(bucket_id,name,metadata) values('insurance-policies',$1,'{}')",[g.id+'/'+randomUUID()],'Unreserved cross-case object path denied');
 await upload(d);
 await fail(finishSQL,[g.id,d.id,1,JSON.stringify(extraction)],'Cross-case completion denied');
 const bad=structuredClone(extraction);bad.fields.premium.value='100000001.00';await fail(finishSQL,[c.id,d.id,1,JSON.stringify(bad)],'Unbounded extraction values rejected');
 const fakeOCR=structuredClone(extraction);fakeOCR.mode='manual_image';await fail(finishSQL,[c.id,d.id,1,JSON.stringify(fakeOCR)],'Images cannot claim extracted values or incorrect mode');
 await finish(c,d);check((await finish(c,d)).id,d.id,'Completion retry is idempotent');
 check((await workspace(c)).history.length,1,'Completion retry creates one upload audit only');
 for(const [reviewed,belongs] of [[false,true],[true,false],[null,true]])await fail(saveSQL,args(c,d,0,undefined,[],reviewed,belongs),'Explicit review and case confirmation required');
 for(const patch of [{premium:''},{premium:'1e6'},{ncd:'101'},{inception:'2026-02-30'},{expiry:'2026-10-10',inception:'2026-10-11'},{registration:'WRONG123'},{unexpected:'x'}])await fail(saveSQL,args(c,d,0,patch),'Invalid or wrong-case reviewed field rejected');
 await root();await db.query("update storage.objects set metadata='{}' where name=$1",[d.path]);await as(office);await fail(saveSQL,args(c,d),'Missing or changed original blocks review save',/Original policy file/);
 await root();await db.query('update storage.objects set metadata=$1 where name=$2',[JSON.stringify({size:123,mimetype:'application/pdf'}),d.path]);await as(office);
 let record=await row(saveSQL,args(c,d));check(record.revision,1,'First explicit review saves revision one');
 check(record.fields.premium,'1250.50','Checked amount saved as exact canonical text');
 check(record.provenance.premium.document_id,d.id,'Saved field retains source original ID');
 check(record.provenance.premium.source.page,1,'Saved suggestion retains source page');
 check(record.provenance.premium.method,'reviewed_local_suggestion','Reviewed extraction distinguished from manual edits');
 await fail(saveSQL,args(c,d,0,{premium:'1300.00'},['premium']),'Concurrent stale review cannot overwrite current fields',/Policy changed/);
 await fail(saveSQL,args(c,d,1,{premium:'1300.00'}),'Conflicting existing value requires exact replacement confirmation');
 record=await row(saveSQL,args(c,d,1,{premium:'1300.00'},['premium']));check(record.fields.insurer,'Synthetic Assurance','Partial review preserves unselected existing fields');
 check(record.provenance.premium.method,'manual_review','Correction records manual provenance');
 const history=(await workspace(c)).history;check(history[0].before_fields.premium,'1250.50','Audit retains earlier premium');check(history[0].after_fields.premium,'1300.00','Audit retains replacement premium');
 await fail('update public.insurance_policy_records set fields=$1',[JSON.stringify({premium:'0'})],'Direct record mutation forbidden');
 await fail("update public.insurance_policy_documents set extraction='{}'",[],'Original extraction evidence immutable to staff');
 await fail("update public.insurance_policy_events set note='changed'",[],'Review audit immutable to staff');
 await db.query("update storage.objects set metadata='{}' where bucket_id='insurance-policies'");check(await scalar("select metadata->>'size' from storage.objects where name=$1",[d.path]),'123','Ready original storage metadata cannot be overwritten');
 await db.query("delete from storage.objects where bucket_id='insurance-policies'");check(await scalar("select count(*)::int from storage.objects where name=$1",[d.path]),1,'Ready originals cannot be deleted by staff');
 await as(office2);const gd=await reserve(g,'a');await upload(gd);await finish(g,gd);await row(saveSQL,args(g,gd));
 check((await workspace(g)).documents[0].id,gd.id,'Same fingerprint in another case gets its own isolated original');
 await fail(saveSQL,args(g,d),'Cannot use another case original for review');
 check(await scalar('select count(*)::int from public.insurance_policy_documents'),1,'Guest Admin sees only assigned policy documents');
 check(await scalar("select count(*)::int from storage.objects where bucket_id='insurance-policies'"),1,'Guest Admin downloads only its assigned policy original');
 await as(sales);check((await workspace(c)).documents[0].id,d.id,'Assigned Sales can read retained policy under existing case boundary');check(await scalar('select count(*)::int from public.insurance_policy_events where case_id=$1',[g.id]),0,'Other case audit remains private');
 await as(office);const pending=await reserve(c,'b');await upload(pending);
 await as(coordinator);check((await workspace(c)).documents.length,1,'Coordinator cannot read another staff incomplete policy');
 const changed=await row('select * from public.e2_assign_finance_admin($1,$2,$3,$4)',[c.id,office2,'Synthetic policy case reassignment',c.revision]);
 await as(office);check(await scalar('select count(*)::int from public.insurance_policy_records'),0,'Previous Admin loses reviewed policy access on reassignment');check(await scalar("select count(*)::int from storage.objects where bucket_id='insurance-policies'"),0,'Previous Admin loses original-file access on reassignment');await fail(finishSQL,[c.id,pending.id,1,JSON.stringify(extraction)],'Late completion after reassignment denied');
 await as(office2);check((await workspace(changed)).documents.length,1,'New assigned Admin receives ready originals only');
 await fail(saveSQL,args(c,d,2,{premium:'1400.00'},['premium']),'Stale case revision denied after reassignment',/Case changed/);
 await fail(finishSQL,[c.id,pending.id,changed.revision,JSON.stringify(extraction)],'New Admin cannot finish someone else pending upload');
 await row(saveSQL,args(changed,d,2,{premium:'1400.00'},['premium']));check((await workspace(changed)).record.fields.premium,'1400.00','New Admin can explicitly review retained original');
 await root();await db.query('update public.staff_memberships set active=false where user_id=$1',[office2]);await as(office2);await fail('select public.e2_policy_workspace($1)',[c.id],'Deactivated Admin loses workspace access');check(await scalar("select count(*)::int from storage.objects where bucket_id='insurance-policies'"),0,'Deactivation revokes all policy downloads');
 await as(owner);check((await workspace(c)).can_write,true,'Super Admin retains existing case override');
 for(let n=2;n<20;n++)await row(reserveSQL,[changed.id,changed.revision,'synthetic-pending.pdf','application/pdf',123,(100+n).toString(16).padStart(64,'0')]);
 await fail(reserveSQL,[changed.id,changed.revision,'synthetic-over-limit.pdf','application/pdf',123,'f'.repeat(64)],'Pending and ready originals share a bounded per-case quota');
 await as(customer);check(await scalar('select count(*)::int from public.insurance_policy_events'),0,'Customer cannot read internal policy review audit');
 await root();check(await scalar("select has_function_privilege('service_role','public.e2_save_policy_review(uuid,uuid,bigint,bigint,jsonb,text[],boolean,boolean,text)','EXECUTE')"),false,'No inherited service-role review RPC grant');
 console.log(`${passed} synthetic insurance policy security/workflow checks passed. No production calls or data.`);await db.close();
})().catch(error=>{console.error(error);process.exitCode=1;});
