import {createHandler,detectMime} from '../functions/e2-guest-intake/handler.mjs';
import assert from 'node:assert/strict';
const id='00000000-0000-4000-8000-000000000001',calls=[],objects=[];
const admin={rpc:async(n,args)=>{calls.push([n,args]);return {data:n==='e2_intake_expired_files'?[]:n==='e2_intake_prepare_file'?{path:'opaque/path',state:'uploading'}:n==='e2_intake_context'?{vehicle:{name:'Test car'}}:n==='e2_intake_begin'?{id,received:false}:{reference:id,received:true}}},storage:{from:b=>({upload:async(p,f,o)=>{objects.push({b,p,size:f.size,o});return{}},remove:async()=>({})})}};
const handler=createHandler(admin);let passed=0;
const check=(v,e,label)=>{assert.deepEqual(v,e);passed++;console.log('PASS '+label)};
const request=(body,origin='https://e2auto.my')=>handler(new Request('https://example.test',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)}));
check((await handler(new Request('https://example.test'))).status,405,'GET not accepted');
check((await request({action:'context',invite:id},'https://evil.test')).status,403,'Unexpected browser origin rejected');
check((await request({action:'context',invite:'not-a-uuid'})).status,400,'Invalid invitation rejected');
check((await request({action:'context',invite:id,website:'bot'})).status,400,'Honeypot rejected');
check((await request({action:'read',target:id,nonce:id})).status,400,'No public read action');
check((await request({action:'download',target:id,nonce:id})).status,400,'No public document action');
check(calls.length,0,'Rejected requests never reach privileged RPC');
const context=await request({action:'context',invite:id});check(context.headers.get('Cache-Control'),'no-store','Private response cache disabled');check((await context.json()).vehicle.name,'Test car','Sanitized context delivered');
check((await request({action:'begin',invite:id,nonce:id,kind:'worker'})).status,200,'Begin dispatch accepted');
check((await request({action:'submit',target:id,nonce:id,details:{},consent:'true',accurate:true,contacts:true})).status,200,'Submit dispatch reaches database validator');check(calls.at(-1)[1].consent,false,'String true cannot bypass consent');
check((await request({action:'context',invite:id,padding:'x'.repeat(70000)})).status,413,'JSON body limit enforced');
for(const [data,mime] of [['%PDF-1.4 synthetic','application/pdf'],[new Uint8Array([255,216,255,0]),'image/jpeg'],[new Uint8Array([137,80,78,71,13,10,26,10]),'image/png']])check(await detectMime(new Blob([data])),mime,'Magic signature detected');
await assert.rejects(()=>detectMime(new Blob(['<html>'],{type:'application/pdf'})));passed++;
const upload=async(content)=>{const f=new FormData();for(const [k,v] of Object.entries({target:id,nonce:id,file_id:id,category:'ic_front',months:'[]'}))f.set(k,v);f.set('file',new Blob([content],{type:'application/pdf'}),'synthetic.pdf');return handler(new Request('https://example.test',{method:'POST',headers:{Origin:'https://e2auto.my'},body:f}))};
check((await upload('<html>')).status,400,'Disguised document blocked before storage');check(objects.length,0,'Rejected content not uploaded');check((await upload('%PDF-1.4 synthetic')).status,200,'Valid upload finalized');check(objects[0].b,'intake-documents','Only private intake bucket used');check(objects[0].p,'opaque/path','Server reservation chooses storage path');check(objects[0].o.upsert,false,'Overwrite disabled');
check(calls.some(([n])=>n.includes('auth')||n.includes('handoff')),false,'Guest endpoint does not create accounts or invoke staff actions');
console.log(passed+' guest endpoint checks passed.');
