import assert from 'node:assert/strict';
import {publicContacts,publicContact,vehicleShareURL,vehiclePageURL,withVehicleLink,enquiryURL,COMPANY_PHONE} from '../../referral.js';
const staff='00000000-0000-4000-8000-000000000001',car='00000000-0000-4000-8000-000000000002';
const config={supabaseUrl:'https://example.supabase.co',publishableKey:'sb_publishable_test'};
const person={user_id:staff,display_name:'Sales & E2',whatsapp:'60123456789'};
let seen;
assert.deepEqual(await publicContact(staff,config,async(url,options)=>{seen={url,options};return {ok:true,json:async()=>[person]}}),person);
assert.equal(seen.options.credentials,'omit');assert.equal(seen.options.headers.Authorization,undefined);
assert.equal(seen.options.cache,'no-store');assert.equal(new URL(seen.url).searchParams.get('is_public'),'eq.true');
assert.equal(new URL(seen.url).searchParams.get('user_id'),'eq.'+staff);
assert.equal(await publicContact('60123456789',config,()=>{throw Error('Must not request')}),null);
assert.equal(await publicContact(staff,config,async()=>({ok:true,json:async()=>[]})),null);
assert.equal(await publicContact(staff,config,async()=>({ok:false})),null);
assert.equal(await publicContact(staff,config,async()=>{throw Error('offline')}),null);
assert.equal(await publicContact(staff,config,async()=>({ok:true,json:async()=>[{...person,whatsapp:'javascript:alert(1)'}]})),null);
assert.equal(await publicContact(staff,config,async()=>({ok:true,json:async()=>[{...person,user_id:car}]})),null);
const url=new URL(vehicleShareURL('https://e2auto.my/profile.html?user='+staff+'&preview=1#old',car,staff));
assert.equal(url.pathname,'/car.html');assert.equal(url.searchParams.get('sales'),staff);assert.equal(url.searchParams.get('id'),car);assert.equal(url.searchParams.has('preview'),false);assert.equal(url.hash,'');
assert.equal(new URL(vehicleShareURL('https://bennychow1979.github.io/e2-auto-web/profile.html',car,staff)).pathname,'/e2-auto-web/car.html');
assert.throws(()=>vehicleShareURL('https://e2auto.my','bad',staff));
const text='Hi Sales & E2, 2017 HONDA CR-V (Plate JMK882). Deposit RM6,199.';
assert.equal(new URL(enquiryURL(person,text)).pathname,'/'+person.whatsapp);
assert.equal(new URL(enquiryURL(person,text)).searchParams.get('text'),text);
assert.equal(new URL(enquiryURL(null,text)).pathname,'/'+COMPANY_PHONE);
assert.equal(new URL(enquiryURL({whatsapp:'https://evil.test'},text)).pathname,'/'+COMPANY_PHONE);
const direct=vehiclePageURL('https://e2auto.my/car.html?preview=1&sales='+staff+'#access_token=private',car);
assert.equal(direct,'https://e2auto.my/car.html?id='+car);
const personal=vehiclePageURL('https://e2auto.my/car.html?update=test',car,staff);
assert.equal(personal,url.href);
assert.equal(vehiclePageURL('https://e2auto.my/',car,'bad'),direct);
assert.throws(()=>vehiclePageURL('https://e2auto.my/','bad'));
const linked=withVehicleLink(text,personal);
assert.equal(new URL(enquiryURL(person,linked)).searchParams.get('text'),text+'\n\nVehicle link: '+personal);
assert.equal(withVehicleLink(linked,personal),linked);
const fallback=withVehicleLink(linked,direct,personal);
assert.equal(fallback,text+'\n\nVehicle link: '+direct);
assert.equal(withVehicleLink(fallback,personal,direct),linked);
assert.equal(new URL(enquiryURL(null,fallback)).pathname,'/'+COMPANY_PHONE);
let listRequest;
assert.deepEqual(await publicContacts(config,async(url,options)=>{listRequest={url,options};return {ok:true,json:async()=>[person,{...person,user_id:'bad'},{...person,whatsapp:'bad'}]}}),[person]);
assert.equal(listRequest.options.credentials,'omit');
assert.equal(listRequest.options.headers.Authorization,undefined);
assert.equal(new URL(listRequest.url).searchParams.get('is_public'),'eq.true');
assert.equal(new URL(listRequest.url).searchParams.get('select'),'user_id,display_name,position,whatsapp');
await assert.rejects(()=>publicContacts({},()=>{throw Error('Should not request')}));
await assert.rejects(()=>publicContacts(config,async()=>({ok:false})));
await assert.rejects(()=>publicContacts(config,async()=>({ok:true,json:async()=>({})})));
let pages=0;
const contacts=await publicContacts(config,async(url)=>{assert.equal(new URL(url).searchParams.get('offset'),String(pages*100));return {ok:true,json:async()=>pages++===0?Array(100).fill(person):[person]}});
assert.equal(contacts.length,101);
assert.equal(pages,2);
console.log('42 referral checks passed.');
