import {db,configured,check,esc,friendlyError} from './e2-data.js?v=customer-1';
const $=id=>document.getElementById(id);let offset=0,query='',busy=false,epoch=0;
const labels={state:'State',city:'City',language:'Language',budget_min:'Budget from (RM)',budget_max:'Budget to (RM)',desired_car:'Preferred car',purchase_timeline:'Purchase timing',payment_preference:'Payment preference',trade_in:'Trade-in',trade_in_details:'Trade-in details'};
function gate(text){epoch++;$('customersList').replaceChildren();$('customersWorkspace').hidden=true;$('customersGate').hidden=false;$('customersGateMessage').textContent=text}
async function load(reset=false){if(busy)return;const run=epoch;busy=true;$('customersSearch').querySelector('button').disabled=true;$('moreCustomers').disabled=true;try{if(reset){offset=0;query=$('customersQuery').value.trim();$('customersList').replaceChildren()}const rows=check(await db.rpc('e2_list_customers',{search_text:query,page_offset:offset}));if(run!==epoch)return;for(const row of rows){const p=row.profile,node=document.createElement('article');node.innerHTML='<h2>'+esc(p.full_name)+'</h2><p>'+esc(row.email)+'<br>'+esc(p.phone)+' · phone not verified</p><details><summary>View preferences</summary><dl>'+Object.entries(labels).map(([key,label])=>'<dt>'+label+'</dt><dd>'+esc(p[key]??'Not specified')+'</dd>').join('')+'<dt>Profile updated</dt><dd>'+esc(new Date(p.updated_at).toLocaleString('en-MY'))+'</dd></dl></details>';$('customersList').append(node)}offset+=rows.length;$('moreCustomers').hidden=rows.length<50;$('customersMessage').textContent=offset?offset+' customer profiles shown.':'No customer profiles found. Profiles appear after email confirmation and profile setup.'}catch(e){if(run===epoch){gate(friendlyError(e));}}finally{busy=false;$('customersSearch').querySelector('button').disabled=false;$('moreCustomers').disabled=false}}
$('customersSearch').onsubmit=e=>{e.preventDefault();load(true)};$('moreCustomers').onclick=()=>load();
$('customersSignOut').onclick=async()=>{try{check(await db.auth.signOut({scope:'local'}));gate('Signed out.')}catch(e){$('customersMessage').textContent=friendlyError(e)}};
if(configured)db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')gate('Signed out.')});
try{if(!configured)throw Error('Customer directory is being prepared.');const session=check(await db.auth.getSession()).session;if(!session||!check(await db.rpc('e2_is_admin')))throw Error('Sign in with an active Admin or Super Admin account.');const member=check(await db.from('staff_memberships').select('role').eq('user_id',session.user.id).single());$('customersAdminEmail').textContent=session.user.email;$('customersTeamLink').hidden=member.role!=='super_admin';$('customersGate').hidden=true;$('customersWorkspace').hidden=false;await load(true)}catch(e){gate(friendlyError(e))}
