import {db,staffView,check,sessionUser,application,documentRows,setType,reserve,finish,remove,storage} from './document-data.js';
import {checklist,applicantTypes,recentMonths,categoryProgress,MAX_BYTES,fileType} from './document-fields.js';
import {esc} from './loan-ui.js';
import {validId} from './saved-intent.js';
const $=id=>document.getElementById(id),main=$('documentMain'),id=new URLSearchParams(location.search).get('application');
let user=null,app=null,rows=[],busy=false,epoch=0,currentItem=null,replacement=null,previewURL=null;
const canEdit=()=>!staffView&&app?.customer_id===user?.id&&['Draft','Submitted to E2','Needs information'].includes(app.status);
const activeRows=()=>rows.filter(r=>!r.removed_at);
function revokePreview(){if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;$('previewContent').replaceChildren();$('previewDialog').close()}
function gate(text){epoch++;user=null;app=null;rows=[];revokePreview();$('uploadDialog').close();main.innerHTML=`<section class="intro"><div><h1>Your documents.</h1><p>${esc(text)}</p><a class="primary" href="${staffView?'portal.html':'my-e2.html?application='+encodeURIComponent(id||'')}">${staffView?'Staff sign in':'Sign in to your application'} ↗</a></div></section>`}
function lock(value){busy=value;document.querySelectorAll('button,input,select').forEach(e=>e.disabled=value)}
function message(text,error=false){const out=$('documentStatus');if(out){out.textContent=text;out.classList.toggle('statusError',error)}}
async function cleanup(){if(staffView)return;const run=epoch;for(const d of rows.filter(r=>r.removed_at)){if(run!==epoch)return;const result=await storage().remove([d.path]);if(result.error)message('A removed file is hidden. Storage cleanup will retry when you reload.',true)}}
async function refresh(){const run=epoch,[a,d]=await Promise.all([application(id,user.id),documentRows(id)]);if(run!==epoch||!user)throw Error('Account changed. Sign in again.');app=a;rows=d;render()}
function render(){const edit=canEdit(),items=checklist(app.applicant_type),shown=activeRows();main.innerHTML=`<section class="intro documentIntro"><div><span class="eyebrow">YOUR APPLICATION · DOCUMENTS</span><h1>A few things<br>to move forward.</h1><p>${esc(app.vehicle_summary.name)} · ${esc(app.vehicle_summary.plate)}</p></div><span class="pill">${esc(app.status)}</span></section><div class="notice">${app.submitted_at?'These files are visible to you, E2 Super Admin and your assigned follow-up employee.':'Your draft files are private to you. E2 can see them only after you submit the application.'}</div><section class="typePanel"><form id="typeForm"><label class="field"><span>Applicant type</span><select id="applicantType" ${edit?'':'disabled'}><option value="">Choose your employment type</option>${applicantTypes.map(([v,t])=>`<option value="${v}" ${app.applicant_type===v?'selected':''}>${t}</option>`).join('')}</select></label>${edit?'<button class="primary">Save checklist type</button>':''}</form><p>Both options are for a vehicle purchased in your own name. IC and driving licence must belong to you.</p></section><div id="documentStatus" class="documentStatus" role="status" aria-live="polite"></div><section class="documentGrid">${items.map(item=>`<article class="documentCard"><header><span class="progress">${esc(categoryProgress(item,shown))}</span><h2>${esc(item.label)}</h2><p>${esc(item.hint)}</p></header>${shown.filter(d=>d.category===item.key).map(d=>`<div class="documentFile"><strong>${esc(d.filename)}</strong><small>${d.state==='ready'?'Uploaded':'Upload incomplete — remove and try again'} · ${(d.byte_size/1048576).toFixed(1)} MB${d.covered_months.length?' · '+esc(d.covered_months.join(', ')):''}</small><div class="fileActions">${d.state==='ready'?`<button data-preview="${d.id}">${d.mime_type==='application/pdf'?'Open PDF':'Preview'}</button>`:''}${edit&&d.state==='ready'?`<button data-replace="${d.id}">Replace</button>`:''}${(!staffView&&(edit||d.state==='uploading'))?`<button data-remove="${d.id}">Remove</button>`:''}</div></div>`).join('')}${edit?`<button class="secondary" data-add="${item.key}">Upload files +</button>`:''}</article>`).join('')}</section><div class="documentFooter"><p>${edit?'You can upload in batches and return later. JPG, PNG or PDF · 10 MB per file · 30 files per application. Select every month covered by a combined PDF.':'Documents are read-only at this stage. E2 can request an update if more files are needed.'} “Uploaded” records receipt of files, not verification or financing approval.</p><a class="primary" href="${$('returnLink').getAttribute('href')}">${staffView?'Back to follow-up':'Continue application'} ↗</a></div>`;
 $('typeForm').onsubmit=async e=>{e.preventDefault();if(busy||!canEdit())return;const kind=$('applicantType').value;lock(true);const run=epoch;try{await setType(app,kind);if(run===epoch)await refresh()}catch(e){if(run===epoch)message(e.message,true)}finally{lock(false);if($('applicantType'))$('applicantType').disabled=!canEdit()}};
}
function openUpload(key,old=null){if(!canEdit()||busy)return;currentItem=checklist(app.applicant_type).find(x=>x.key===key);if(!currentItem)return;replacement=old;$('uploadForm').reset();$('documentFiles').multiple=!old&&!currentItem.months;$('uploadTitle').textContent=(old?'Replace ':'Upload ')+currentItem.label;$('uploadHint').textContent=old?'The original stays available until the replacement uploads successfully.':currentItem.hint+(currentItem.months?' · Choose one file at a time and mark its months. A combined PDF may cover several months.':'');$('uploadMessage').textContent='';$('monthFields').hidden=!currentItem.months;$('monthChoices').innerHTML=recentMonths().map(m=>`<label><input type="checkbox" value="${m}" ${old?.covered_months.includes(m)?'checked':''}>${m}</label>`).join('');$('uploadDialog').showModal()}
async function preview(doc){if(busy)return;lock(true);const run=epoch;try{const blob=check(await storage().download(doc.path));const mime=await fileType(blob);if(run!==epoch)return;revokePreview();previewURL=URL.createObjectURL(new Blob([blob],{type:mime}));$('previewTitle').textContent=doc.filename;const content=$('previewContent');if(mime==='application/pdf'){const note=document.createElement('p');note.textContent='Your PDF is ready. Download it to open all pages in your device’s PDF viewer.';content.append(note)}else{const img=document.createElement('img');img.alt='Uploaded document preview';img.src=previewURL;content.append(img)}const link=document.createElement('a');link.className='secondary';link.href=previewURL;link.download=doc.filename;link.textContent='Download file';content.append(link);$('previewDialog').showModal()}catch(e){if(run===epoch)message(e.message||'Could not open this file.',true)}finally{lock(false);if($('applicantType'))$('applicantType').disabled=!canEdit()}}
main.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.add)openUpload(b.dataset.add);const doc=rows.find(d=>d.id===(b.dataset.preview||b.dataset.replace||b.dataset.remove));if(!doc)return;if(b.dataset.preview)preview(doc);if(b.dataset.replace)openUpload(doc.category,doc);if(b.dataset.remove){if(!confirm('Remove this uploaded file? You can upload it again if needed.'))return;lock(true);const run=epoch;try{await remove(doc);check(await storage().remove([doc.path]));if(run===epoch)await refresh()}catch(e){if(run===epoch){try{await refresh()}catch{}message(e.message||'File cleanup failed. Reload to retry.',true)}}finally{lock(false);if($('applicantType'))$('applicantType').disabled=!canEdit()}}});
$('uploadForm').onsubmit=async e=>{e.preventDefault();if(busy||!canEdit())return;const files=[...$('documentFiles').files],months=[...$('monthChoices').querySelectorAll('input:checked')].map(x=>x.value),run=epoch,item=currentItem,old=replacement;let saved=0;
 if(!files.length||(old||item.months)&&files.length!==1){$('uploadMessage').textContent='Choose '+(old?'one replacement file.':item.months?'one statement file at a time.':'at least one file.');return}if(item.months&&(months.length<1||months.length>item.months)){$('uploadMessage').textContent=`Select 1–${item.months} months covered by these files.`;return}if(activeRows().length+files.length>30){$('uploadMessage').textContent='Maximum 30 files. Remove an old file or combine pages into a PDF.';return}
 lock(true);try{const prepared=[];for(const f of files){if(f.size<1||f.size>MAX_BYTES)throw Error(f.name+': choose a file up to 10 MB.');if(f.name.length>160)throw Error('Shorten the file name to 160 characters.');prepared.push([f,await fileType(f)])}
 for(const [file,mime] of prepared){if(run!==epoch)break;$('uploadMessage').textContent=`Uploading ${saved+1} / ${files.length}: ${file.name}`;const reserved=await reserve(id,item,file,mime,item.months?months:[]);if(run!==epoch)break;try{check(await storage().upload(reserved.path,file,{contentType:mime,cacheControl:'0',upsert:false}));if(run!==epoch)break;await finish(reserved,old?.id);saved++}catch(error){if(run!==epoch)break;let state;try{state=(await documentRows(id)).find(r=>r.id===reserved.id)}catch{}if(state?.state==='ready'&&!state.removed_at){saved++;continue}if(state?.state==='uploading'){try{await remove(state);await storage().remove([state.path])}catch{}}throw error}}
 if(run===epoch){$('uploadDialog').close();await refresh();await cleanup();message(`${saved} file${saved===1?'':'s'} uploaded and saved.`)}
 }catch(e){if(run===epoch){$('documentFiles').value='';$('uploadMessage').textContent=`${saved?`${saved} file(s) saved. Select only the remaining files to retry. `:''}${e.message||'Upload interrupted. Reload to check the saved files before retrying.'}`;try{await refresh()}catch{}}}finally{lock(false);if($('applicantType'))$('applicantType').disabled=!canEdit()}};
$('closeUpload').onclick=()=>{if(!busy)$('uploadDialog').close()};$('uploadDialog').addEventListener('cancel',e=>{if(busy)e.preventDefault()});$('closePreview').onclick=revokePreview;$('previewDialog').addEventListener('close',()=>{if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;$('previewContent').replaceChildren()});
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue=''}});db?.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||user&&session?.user&&session.user.id!==user.id)gate('Sign in to view your documents.')});
try{if(!db||!validId(id))throw Error('Open Documents from your loan application.');const run=epoch,who=await sessionUser();if(run===epoch){if(!who)throw Error('Sign in to view your documents.');user=who;$('returnLink').href=staffView?'loans.html':'my-e2.html?application='+id;await refresh();if(run===epoch)await cleanup()}}catch(e){gate(e.message||'Documents are temporarily unavailable.')}
