import {sections,visibleField,steps} from './loan-fields.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const rm=n=>'RM'+Number(n).toLocaleString('en-MY');
export function renderField([key,label,sub,type,required],details,price){const value=details[key]??'',attrs=`id="field_${key}" name="${key}" ${required?'required':''} autocomplete="off"`;let control;
 if(Array.isArray(type)||type==='year'||type==='months'){const choices=Array.isArray(type)?type:type==='year'?Array.from({length:new Date().getFullYear()-1939},(_,i)=>String(new Date().getFullYear()-i)):Array.from({length:12},(_,i)=>String(i));control=`<select ${attrs}><option value="">Choose an option</option>${choices.map(x=>`<option ${String(value)===x?'selected':''}>${esc(x)}</option>`).join('')}</select>`}
 else if(type==='textarea')control=`<textarea ${attrs} maxlength="300" rows="2">${esc(value)}</textarea>`;
 else control=`<input ${attrs} type="${type}" value="${esc(value)}" ${type==='number'?`min="0" max="${key==='deposit'?price:key.includes('work_')?80:99999999}" step="1"`:'maxlength="150"'}>`;
 return `<label class="field ${type==='textarea'?'full':''}" data-field="${key}"><span>${label}${required?' *':''}<span class="sub">${sub}</span></span>${control}</label>`;
}
export function renderStep(i,details,price){const specs=sections(details)[i];let html='';for(const [n,spec] of specs.entries()){if(spec[0]==='e1_name'||spec[0]==='e2_name'||spec[0]==='g_name'||spec[0]==='g_address'||spec[0]==='g_company'||spec[0]==='g_marriage_cert'){html+=`${n?'</div>':''}<h3 class="formSection">${esc({'e1_name':'Emergency contact 1','e2_name':'Emergency contact 2','g_name':'Guarantor details','g_address':'Guarantor address','g_company':'Guarantor employment','g_marriage_cert':'Guarantor supporting details'}[spec[0]])}</h3><div class="fields">`}else if(n===0)html+='<div class="fields">';if(visibleField(spec[0],details))html+=renderField(spec,details,price)}return html+'</div>'}
export function renderReview(details,{editable=false}={}){return sections(details).map((specs,i)=>`<section class="reviewGroup"><div class="reviewHead"><h3>${i+1}. ${steps[i]}</h3>${editable?`<button type="button" class="textButton" data-step="${i}">Edit ↗</button>`:''}</div><dl class="reviewGrid">${specs.filter(([k])=>visibleField(k,details)).map(([key,label])=>`<div><dt>${key.startsWith('e1_')?'Emergency contact 1 · ':key.startsWith('e2_')?'Emergency contact 2 · ':''}${label}</dt><dd>${esc(details[key]||'Not provided')}</dd></div>`).join('')}</dl></section>`).join('')}
