const yesno=['Yes','No','Not applicable'];
export const personal=[['name','Full name','Nama seperti I/C','text',true],['ic','I/C number','No. I/C','text',true],['old_ic','Old I/C number','No. I/C lama · optional','text'],['phone','Mobile / WhatsApp','No. H/P','tel',true],['email','Email','Alamat e-mel','email',true],['marital','Marital status','Status perkahwinan',['Single','Married','Divorced','Widowed'],true],['phone_model','Phone model','Model telefon · optional','text']];
export const address=[['address','Current home address','Alamat kediaman sekarang','textarea',true],['since','Living here since','Tinggal mulai tahun','year',true],['housing','Current residence','Rumah kediaman sekarang',['Rented / Sewa','Parents’ home / Rumah ibu bapa','Own home / Rumah sendiri'],true],['hometown','Hometown address','Alamat kampung','textarea',true]];
export const employment=[['company','Company name','Nama syarikat','text',true],['position','Position','Jawatan','text',true],['work_years','Years employed','Tempoh bekerja · tahun','number',true],['work_months','Additional months','Tempoh bekerja · bulan','months'],['office_address','Office address','Alamat pejabat','textarea',true],['office_phone','Office telephone','No. tel pejabat','tel',true],['interview','Best time for an interview call','Pukul berapa sesuai untuk panggilan',['9:00 am – 12:00 pm','12:00 pm – 2:00 pm','2:00 pm – 5:00 pm','Please arrange with me'],true]];
export const support=[['marriage_cert','Marriage certificate available?','Sijil perkahwinan',yesno,true],['birth_cert','Birth certificate available?','Sijil kelahiran',yesno,true],['credit','Known credit / overdue debt issues?','Maklumat sendiri · bukan keputusan bank',['No known issues','Yes','Not sure'],true],['debt','Outstanding amount (RM)','Jumlah hutang · if known','number']];
export const contact=[['name','Full name','Nama','text',true],['phone','Phone number','No. tel','tel',true],['relation','Relationship','Hubungan',['Spouse','Parent','Sibling','Relative','Friend','Other'],true],['ic','I/C number','No. I/C · optional','text'],['address','Address','Alamat · optional','textarea'],['position','Occupation / position','Jawatan · optional','text']];
export const finance=[['deposit','Preferred deposit (RM)','Anggaran wang pendahuluan','number',true],['tenure','Preferred tenure','Tempoh pembiayaan',['3 years','4 years','5 years','6 years','7 years','8 years','9 years'],true]];

export const steps=['Vehicle','Personal details','Address','Employment','Supporting details','Guarantor','Review & submit'];
export const titles=['The car. Your plans.','Let’s start with you.','A place to call home.','Tell us about your work.','A few more details.','Someone by your side.','Take one last look.'];
export const prefixed=(arr,prefix)=>arr.map(a=>[prefix+a[0],...a.slice(1)]);
export const guarantorChoice=['guarantor','Is a guarantor needed?','Penjamin',['Not requested','Yes','Not sure'],true];
export const guarantorFields=[...personal,['relation','Relationship with hirer','Hubungan dengan pemohon',['Spouse','Parent','Sibling','Relative','Other'],true],...address,...employment,...support];
export function sections(details={}) {return [finance,personal,address,employment,[...support,...prefixed(contact,'e1_'),...prefixed(contact,'e2_')],[guarantorChoice,...(details.guarantor==='Yes'?prefixed(guarantorFields,'g_'):[])]]}
export function visibleField(key,d){if(key==='debt')return d.credit==='Yes';if(key==='g_debt')return d.guarantor==='Yes'&&d.g_credit==='Yes';return !key.startsWith('g_')||d.guarantor==='Yes'}
export function missingSteps(d){return sections(d).map((fields,i)=>fields.some(([k,l,s,t,required])=>required&&visibleField(k,d)&&!String(d[k]??'').trim())?i:null).filter(i=>i!==null)}
export function submissionDetails(details){return Object.fromEntries(Object.entries(details).filter(([key])=>visibleField(key,details)))}
