import {db,check} from './e2-data.js';
import {renderReview,esc,rm} from './loan-ui.js';
const main=document.getElementById('staffLoans'),$=id=>document.getElementById(id);
let isSuper=false,active=null,staff=[],busy=false,epoch=0,offset=0;
const transitions={'Submitted to E2':['Needs information','Ready for financier'],'Ready for financier':['Needs information','Submitted to financier'],'Submitted to financier':['Needs information','Outcome recorded']};
const date=v=>new Date(v).toLocaleString('en-MY',{dateStyle:'medium',timeStyle:'short'});
function lock(v){busy=v;main.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=v)}
function gate(text){epoch++;active=null;staff=[];isSuper=false;main.innerHTML=`<section class="intro"><div><h1>Loan follow-up.</h1><p>${esc(text)}</p><a class="primary" href="portal.html">Staff sign in ↗</a></div></section>`;$('staffLoanSignOut').hidden=true}
async function list(reset=true){if(busy)return;lock(true);const run=++epoch;try{if(reset){offset=0;active=null;main.innerHTML='<section class="intro"><div><span class="eyebrow">E2 FOLLOW-UP</span><h1>Every next step.</h1><p>Submitted applications within your assigned access. Customer drafts stay private.</p></div></section><p id="staffLoanMessage" role="status"></p><div id="staffLoanRows"></div><button class="secondary" id="moreLoans">Load more</button>'}
 const rows=check(await db.from('loan_applications').select('id,vehicle_summary,status,updated_at,assigned_sales').not('submitted_at','is',null).order('updated_at',{ascending:false}).order('id').range(offset,offset+49));if(run!==epoch)return;
 $('staffLoanRows').insertAdjacentHTML('beforeend',rows.map(a=>`<article class="appRow" style="grid-template-columns:1fr auto"><div><span class="pill">${esc(a.status)}</span><h3>${esc(a.vehicle_summary.name)} · ${esc(a.vehicle_summary.plate)}</h3><p>Reference ${a.id}</p><p>${esc(date(a.updated_at))}${!a.assigned_sales?' · Awaiting assignment':''}</p></div><button class="primary" data-loan="${a.id}">Open application ↗</button></article>`).join(''));offset+=rows.length;$('staffLoanMessage').textContent=offset?offset+' applications shown.':'No submitted applications within your access.';$('moreLoans').hidden=rows.length<50;$('moreLoans').onclick=()=>list(false);
 }catch(e){gate(e.message||'Could not load applications.')}finally{lock(false)}}
async function open(id){if(busy)return;lock(true);const run=++epoch;try{const a=check(await db.from('loan_applications').select('*').eq('id',id).single());const events=check(await db.from('loan_events').select('event,note,created_at').eq('application_id',id).order('id'));if(run!==epoch)return;active=a;
 main.innerHTML=`<button class="backLink" id="backLoans">← Applications</button><section class="intro"><div><span class="eyebrow">${esc(a.status)}</span><h1>${esc(a.details.name||'Application')}</h1><p>${esc(a.vehicle_summary.name)} · ${esc(a.vehicle_summary.plate)} · ${rm(a.vehicle_summary.price)}</p><p>Reference ${a.id}</p></div></section><div class="notice">Applicant details are read-only for staff. Request information so the customer can make corrections. Record actual progress only; this site does not submit to a bank or decide eligibility.</div><section class="wizardBody"><p><a class="primary" href="documents.html?application=${a.id}&staff=1">View supporting documents ↗</a></p><h2>Follow-up</h2>${isSuper?`<form id="assignLoan"><label class="field"><span>Assigned salesperson / Office Admin</span><select name="sales"><option value="">E2 team — unassigned</option>${staff.map(s=>`<option value="${s.user_id}" ${s.user_id===a.assigned_sales?'selected':''}>${esc(s.email)} · ${esc(s.role)}</option>`).join('')}</select></label><p class="requiredHint">The assigned person can read this submitted application's IC, contact and financial details, including uploaded documents.</p><button class="secondary">Save assignment</button></form>`:''}${transitions[a.status]?`<form id="statusLoan"><label class="field"><span>Next recorded step</span><select name="status">${transitions[a.status].map(s=>`<option>${s}</option>`).join('')}</select></label><label class="field"><span>Customer-facing explanation / actual outcome</span><textarea name="note" required maxlength="1000" rows="3"></textarea></label><button class="primary">Update progress</button></form>`:'<p>Waiting for the customer, or no further status transition is available.</p>'}<p class="formError" id="staffLoanError" role="alert"></p><h2>History</h2><ol class="timeline">${events.map(e=>`<li class="done">${esc(e.event)}<small>${esc(date(e.created_at))}</small><p>${esc(e.note)}</p></li>`).join('')}</ol><h2>Submitted details</h2>${renderReview(a.details)}</section>`;
 $('backLoans').onclick=()=>list();
 if($('assignLoan'))$('assignLoan').onsubmit=async e=>{e.preventDefault();const sales=e.currentTarget.elements.sales.value;if(!confirm('Give this assigned staff member access to the submitted application and record the reassignment?'))return;await update('e2_assign_loan',{sales:sales||null})};
 if($('statusLoan'))$('statusLoan').onsubmit=async e=>{e.preventDefault();await update('e2_update_loan_status',{next_status:e.currentTarget.elements.status.value,message:e.currentTarget.elements.note.value.trim()})};
 main.focus();window.scrollTo({top:0,behavior:'instant'});
 }catch(e){gate(e.message||'Application unavailable.')}finally{lock(false)}}
async function update(fn,params){if(busy)return;lock(true);const run=epoch,id=active.id;try{check(await db.rpc(fn,{target:id,expected_revision:active.revision,...params}));if(run!==epoch)return;busy=false;await open(id)}catch(e){if(run===epoch&&$('staffLoanError'))$('staffLoanError').textContent=e.message||'Could not save. Reload and try again.'}finally{lock(false)}}
main.addEventListener('click',e=>{const b=e.target.closest('[data-loan]');if(b)open(b.dataset.loan)});
$('staffLoanSignOut').onclick=async()=>{if(busy)return;try{check(await db.auth.signOut({scope:'local'}));gate('Signed out.')}catch(e){gate(e.message)}};
db?.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')gate('Sign in to view applications.')});
try{const run=epoch;if(!db)throw Error('Staff connection unavailable.');const session=check(await db.auth.getSession()).session;if(!session)throw Error('Sign in with your staff account.');const m=check(await db.from('staff_memberships').select('role,active').eq('user_id',session.user.id).single());if(!m.active||!['super_admin','admin','office_admin','sales'].includes(m.role))throw Error('Application follow-up access required.');const superAccess=check(await db.rpc('e2_is_super_admin')),members=superAccess?check(await db.rpc('e2_list_staff')).filter(s=>s.active&&['super_admin','admin','office_admin','sales'].includes(s.role)):[];if(run===epoch){if(m.role==='office_admin'){document.querySelector('a[href="profile.html"]').hidden=true;const home=document.querySelector('nav a[href="portal.html"]');home.textContent='Customer intake';home.href='intake-workspace.html'}isSuper=superAccess;staff=members;$('staffLoanSignOut').hidden=false;await list()}}catch(e){gate(e.message||'Could not check staff access.')}
