import {db,configured,check,friendlyError} from './e2-data.js?v=profile-1';
import {normalizeWhatsApp,portraitBlob,unwrapProfile} from './profile-utils.js';
const $=id=>document.getElementById(id),form=$('profileForm'),fallback='assets/e2-logo.png';
const roles={super_admin:'Super Admin',admin:'Admin',sales:'Salesman',account:'Account'};
let me,target,superAdmin=false,saved=null,pendingBlob=null,portraitURL=null,photoRemoved=false,busy=false,dirty=false,epoch=0;
function note(text,bad=false){$('profileMessage').textContent=text;$('profileMessage').classList.toggle('error',bad)}
function lock(value){busy=value;$('profileFields').disabled=value;['staffPicker','reloadProfile','publishProfile','profileSignOut'].forEach(id=>$(id).disabled=value)}
function gate(text){epoch++;$('profileWorkspace').hidden=true;$('profileGate').hidden=false;$('gateMessage').textContent=text;form.reset();if(portraitURL)URL.revokeObjectURL(portraitURL);portraitURL=null;pendingBlob=null;saved=null;dirty=false}
function portrait(src){$('editPortrait').src=src;$('previewPortrait').src=src}
function preview(){$('previewName').textContent=form.elements.display_name.value.trim()||'Your name';for(const field of ['position','languages','bio'])$('preview'+field[0].toUpperCase()+field.slice(1)).textContent=form.elements[field].value;$('previewWhatsApp').textContent=form.elements.whatsapp.value.trim()||'Add your WhatsApp number'}
function visibility(){const published=saved?.is_public===true;$('visibilityState').textContent=published?'Published · visible to customers.':'Private · visible only to you and Super Admin.';$('publishControls').hidden=!superAdmin;$('publishProfile').textContent=published?'Make private':'Publish profile';$('publishProfile').disabled=busy||!saved||dirty;$('publicProfileLink').hidden=!published;$('publicProfileLink').href='consultant.html?id='+target}
async function loadProfile(){const request=++epoch;lock(true);try{const row=check(await db.from('staff_profiles').select('*').eq('user_id',target).maybeSingle());let src=fallback;if(row?.photo_path){const result=await db.storage.from('staff-photos').createSignedUrl(row.photo_path,300);if(!result.error)src=result.data.signedUrl}if(request!==epoch)return;saved=row;pendingBlob=null;photoRemoved=false;if(portraitURL)URL.revokeObjectURL(portraitURL);portraitURL=null;form.reset();for(const field of ['display_name','position','whatsapp','languages','bio'])form.elements[field].value=row?.[field]||'';portrait(src);dirty=false;preview();visibility();note(row?'Saved profile loaded.':'Add your details, then save your profile.')}catch(e){gate('Could not load this profile. '+friendlyError(e))}finally{if(request===epoch){lock(false);visibility()}}}
form.oninput=()=>{dirty=true;preview();visibility()};
$('portraitInput').onchange=async()=>{const file=$('portraitInput').files[0];if(!file||busy)return;const request=epoch;lock(true);try{const blob=await portraitBlob(file);if(request!==epoch)return;if(portraitURL)URL.revokeObjectURL(portraitURL);pendingBlob=blob;photoRemoved=false;portraitURL=URL.createObjectURL(blob);portrait(portraitURL);dirty=true;note('Photo prepared. Save profile to upload it.')}catch(e){note(friendlyError(e),true)}finally{if(request===epoch){$('portraitInput').value='';lock(false);visibility()}}};
$('removePortrait').onclick=()=>{if(busy)return;if(portraitURL)URL.revokeObjectURL(portraitURL);portraitURL=null;pendingBlob=null;photoRemoved=true;dirty=true;portrait(fallback);visibility()};
form.onsubmit=async event=>{event.preventDefault();if(busy)return;const request=epoch,staffId=target,previous=saved?.photo_path;let uploaded=null;lock(true);note('Saving profile…');try{const details=Object.fromEntries(['display_name','position','whatsapp','languages','bio'].map(f=>[f,form.elements[f].value.trim()]));details.whatsapp=normalizeWhatsApp(details.whatsapp);details.photo_path=photoRemoved?null:previous||null;if(pendingBlob){uploaded=staffId+'/'+crypto.randomUUID()+'.webp';check(await db.storage.from('staff-photos').upload(uploaded,pendingBlob,{contentType:'image/webp',upsert:false}));details.photo_path=uploaded}
const row=unwrapProfile(check(await db.rpc('e2_save_profile',{target:staffId,details,expected_revision:saved?.revision||0})));uploaded=null;if(previous&&previous!==row.photo_path)await db.storage.from('staff-photos').remove([previous]);if(request!==epoch)return;saved=row;pendingBlob=null;photoRemoved=false;dirty=false;form.elements.whatsapp.value=row.whatsapp;preview();note('Profile saved. A Super Admin can now publish it.');visibility()}catch(e){if(uploaded)await db.storage.from('staff-photos').remove([uploaded]);if(request===epoch)note(friendlyError(e),true)}finally{if(request===epoch){lock(false);visibility()}}};
$('publishProfile').onclick=async()=>{if(busy||dirty||!saved)return;lock(true);try{saved=unwrapProfile(check(await db.rpc('e2_publish_profile',{target,visible:!saved.is_public,expected_revision:saved.revision})));note(saved.is_public?'Profile published. Customers can open your public profile.':'Profile is now private.')}catch(e){note(friendlyError(e),true)}finally{lock(false);visibility()}};
$('reloadProfile').onclick=()=>{if(!busy&&(!dirty||confirm('Discard unsaved profile changes and reload?')))loadProfile()};
$('staffPicker').onchange=()=>{if(dirty&&!confirm('Discard unsaved profile changes?')){$('staffPicker').value=target;return}target=$('staffPicker').value;history.replaceState(null,'','profile.html?user='+target);loadProfile()};
$('profileSignOut').onclick=async()=>{if(busy||(dirty&&!confirm('Discard unsaved profile changes and sign out?')))return;try{check(await db.auth.signOut());gate('Signed out.')}catch(e){note(friendlyError(e),true)}};
if(configured)db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')gate('Sign in to edit your staff profile.')});
try{if(!configured)throw Error('Workspace connection is not configured.');const session=check(await db.auth.getSession()).session;if(!session)throw Error('Sign in to edit your staff profile.');me=session.user;const member=check(await db.from('staff_memberships').select('role,active').eq('user_id',me.id).maybeSingle());if(!member?.active||!roles[member.role])throw Error('An active staff account is required.');superAdmin=member.role==='super_admin';target=new URLSearchParams(location.search).get('user')||me.id;if(!/^[0-9a-f-]{36}$/.test(target)||!check(await db.rpc('e2_profile_editor',{target})))throw Error('You cannot edit this staff profile.');
$('accountEmail').textContent=me.email;$('accountRole').textContent=roles[member.role];$('teamLink').hidden=!superAdmin;if(superAdmin){const rows=check(await db.rpc('e2_list_staff'));for(const row of rows.filter(r=>roles[r.role])){const option=document.createElement('option');option.value=row.user_id;option.textContent=row.email+(row.active?'':' · inactive');$('staffPicker').append(option)}$('staffPicker').value=target;$('staffPickerField').hidden=false}
$('profileGate').hidden=true;$('profileWorkspace').hidden=false;await loadProfile()}catch(e){gate(friendlyError(e))}
window.addEventListener('beforeunload',event=>{if(busy||dirty){event.preventDefault();event.returnValue=''}});
